### ISSUE TITLE
Add admonition to MKDocs

### ISSUE THREAD

**Issue by idiazroncero** [Metadrop/drupal-boilerplate#21]
We are using [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions) on our documentations in order to raise awareness about errors, warnings, notes, etc.

I think we should have this included by default on our mkdocs config. It is bundled with Material MKdocs (but inactive by default). It is as easy as adding

```yaml
markdown_extensions:
  - admonition
```
 to the mkdocs.yml file.

**Comment by jorgetutor** [comment]
+1

**Comment by idiazroncero** [comment]
PR ready.
