### ISSUE TITLE
Avoid 'port collision'

### ISSUE THREAD

**Issue by Eduardo-Morales-Alberti** [Metadrop/drupal-boilerplate#30]
- Problem description
When tries to up a project using traefik container, it collides with any other port that may match.

```
ERROR: for traefik  Cannot start service traefik: driver failed programming external connectivity on endpoint example_traefik (128fe0fe0b5fb6ed9313d45deac65dbff40db50722d72332f7dae2d770b7e68f): Bind for 0.0.0.0:8444 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
````

- Issue reference https://stackoverflow.com/questions/48281970/how-do-i-avoid-port-collision-when-using-docker#answer-48282026

- Original docker documentation https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
```
Either specify both ports (HOST:CONTAINER), or just the container port (an ephemeral host port is chosen).
```
- Proposed solution:

Do not set the external port, only the internal docker port.
Example:
```
  traefik:
    ports:
     - '80'
     - '443'
```
Then show the url, and set it on the multiple files, like local.drush.yml
```
docker-compose port traefik 80
0.0.0.0:32769
```

**Comment by Eduardo-Morales-Alberti** [comment]
Related pull request https://github.com/Metadrop/scripthor/pull/10

**Comment by omarlopesino** [comment]
Thanks!
We can consider this finished as the [MR](https://github.com/Metadrop/scripthor/pull/10) is merged, and the boilerplate requires the latest version of the library. Closing.
