### ISSUE TITLE
Create make command to setup the site

### ISSUE THREAD

**Issue by omarlopesino** [Metadrop/drupal-boilerplate#45]
This command will be useful to start developing in an existing project.

The command should:

- Copy all the specific site files:
   - docker-compose.override.yml
   - settings.local.php
   - ...
- Up the environment.
- Execute reload local. It will contain additional commented lines to install the site.

**Comment by Esrohym** [comment]
Hello @mistermoper mind reviewing this [PR](https://github.com/Metadrop/drupal-boilerplate/pull/46/files)?

**Comment by omarlopesino** [comment]
This task hasn't finally been managed through this issue. Closing the issue.
