### ISSUE TITLE
Add drupal/componentes as a dependency to avoid error

### ISSUE THREAD

**Issue by idiazroncero** [Metadrop/drupal-boilerplate#59]
![Screenshot_20220225_143017](https://user-images.githubusercontent.com/3958741/155723642-2abc77eb-0aef-49ac-b4e0-e9282bf1b7cc.png)

drupal/componentes module has been a dependency of theme Radix for a while, but it's not included on this repo's composer.json. In the past, this wasn't a problem because themes couldn't declare module dependencies. But now, Drupal themes can declare module dependencies and this causes the theme install to fail. 

## Proposed solution

Add drupal/componentes as a dependency.

**Comment by rsanzante** [comment]
Thanks! It should be fixed in v2.0.0-alpha3

**Comment by rsanzante** [comment]
v2.0.0-alpha3 ready!
