### ISSUE TITLE
After successful install, `make info` command fails

### ISSUE THREAD

**Issue by idiazroncero** [Metadrop/drupal-boilerplate#60]
Output:

```sh
Traceback (most recent call last):
  File "scripts/parse_yml.py", line 7, in <module>
    import yaml
ImportError: No module named yaml
make: *** [Makefile:19: info] Error 1
```

Running on a Kubuntu impish 21.10 kernel version 5.13.0-30-generic, python version is 2.7.18.
drupal-boilperlate version was 2.0.0:

```
Installing metadrop/drupal-boilerplate (v2.0.0)
  - Installing metadrop/drupal-boilerplate (v2.0.0): Extracting archive
```

**Comment by idiazroncero** [comment]
Follow up;

As it seems, it is normal (see https://askubuntu.com/questions/103469/how-do-i-change-my-pythonpath-to-make-3-2-my-default-python-instead-of-2-7-2) to have both a `python` (v2) and `python3` (v3) on the CLI. I don't know if this is by default, or is a result of having upgraded my Kubuntu from older versions, but it looks like a normal thing to have.

It also looks like python2 misses the yaml extension while python3 has it included by default. The scripts seems to be executed using v2 (`python`), so installing the yaml extension for v2 should suffice.

Sadly, getting the yaml extension isn't as easy. Python2 instructs you tu use apt-get instad of pip when you try it, and on newer kubuntu versions, `apt-get install python-yaml` throws an "obsolete or deprecated" result and won't install.

If you manually use `python3 scripts/get_info.sh`, it works.

So, the only ways to make this work on environments like mine is:

- Manually use python3
- Find a way to install python-yaml extension for python2 (using some repository of obsolete/deprecated python extensions for python2)
- Run this command from within a docker container that has the correct python version and extensions built-in.

Maybe this could be documented somehow, on a troublesome/faqs section on the docs in order to help users with the same problem.

**Comment by rsanzante** [comment]
_Maybe this could be documented somehow, on a troublesome/faqs section on the docs in order to help users with the same problem._

Yes, your are right. This is fairly new and we need to check it in different environments/OS.

Python 3 is needed with yaml extension. Python 3 is the preferred Python release, specially because Python 2 has reached its End of Life.

You may select pyhton3 as default using:

```update-alternatives --config python```

This is for Debian-like systems.


**Pending**
Add some docs.

**Comment by rsanzante** [comment]
Added documentation on v2.0.0-alpha3.
