### ISSUE TITLE
Generate backstop references by scenario

### ISSUE THREAD

**Issue by franrou** [Metadrop/drupal-boilerplate#88]
Update the make backstop-references command to allow filter by scenario name and only generate the references for the targeted scenario

`make backstopjs-reference [scenario-name]`

**Comment by Eduardo-Morales-Alberti** [comment]
@franrou could you add documentation on how to generate the reference?

**Comment by franrou** [comment]
@Eduardo-Morales-Alberti done

**Comment by jorgetutor** [comment]
@franrou could you please remark in the documentation that this extra parameter is optional and that will generate all without it?

**Comment by Eduardo-Morales-Alberti** [comment]
@jorgetutor Changes applied, could you review them?

**Comment by Eduardo-Morales-Alberti** [comment]
Pending to add the filter also to test cc @franrou

**Comment by franrou** [comment]
@Eduardo-Morales-Alberti Filter parameter was added to to the backstopjs-test command

Ready to review
